
# Configuration for PDF → Text → JSON pipeline (v0.4)
input_dir: input_pdfs
output_dir: outputs

# OCR
ocr_lang: en              # en | te | hi | mr | ta | mixed
ocr_engine: easyocr       # easyocr | tesseract | paddle
ocr_endpoint: null        # if using paddle as HTTP service

# Layout
layout_strategy: docling  # docling | hybrid | native

# Logging & cleanup
verbose: 1
print_every: 5
max_cleanups: 10
final_only: 0

domain_cleanup:
  enabled: true           # turn the pass on/off
  domain: histopathology  # domain dictionary to use (extensible)
  fuzzy_cutoff: 0.86      # higher = stricter corrections
  max_corrections: 200    # cap auto-fixes per block

# LLM
ollama_model: alibayram/medgemma
small_fallback_model: mistral:7b
ollama_url: http://localhost:11434
ollama_max_secs: 60
final_chunk_size: 20
max_retries_final: 3
shrink_factor: 0.7

# Validation & perf
validate_json: 0
workers: 1
max_image_ocr: 8
cache_dir: .cache_ocr
enable_cache: 0

# Docling options
docling_doc_prepass: 0

# Observability
enable_summaries_csv: 1

# Schema control
active_schema: prescription
schemas:
  prescription:
    patient: {name: "", age: "", sex: "", id: "", date: "", contact: "", address: ""}
    doctor: {name: "", registration_no: "", qualification: "", clinic: "", contact: "", address: ""}
    diagnosis: ""
    complaints: ""
    medications:
      - {drug: "", strength: "", route: "", sig: "", frequency: "", duration: "", quantity: "", timing: "", notes: ""}
    tests: []
    investigations: []
    advice: ""
    follow_up: ""
    metadata: {pages: 0, sources: [], languages: []}

  lab_report:
    report_type: "lab"
    patient: {name: "", age: "", sex: "", uhid: "", cr_no: "", contact: "", address: ""}
    facility: {name: "", department: "", location: ""}
    report_details: {accession_no: "", sample_collected: "", sample_received: "", report_date: "", clinical_details: ""}
    results:
      - {test: "", value: "", unit: "", ref_range: "", flag: ""}
    comments: ""
    advice: ""
    validated_by: ""
    metadata: {pages: 0, sources: [], languages: []}

  medical_report:
    report_type: ""
    patient: {name: "", age: "", sex: "", uhid: "", cr_no: "", abha_no: "", contact: "", address: ""}
    facility: {name: "", department: "", location: ""}
    report_details: {study_date: "", acceptance_date: "", reporting_date: "", specimen_type: "", clinical_details: ""}
    findings: {gross: "", microscopy: "", impression: "", results: []}
    medications: []
    tests: []
    advice: ""
    validated_by: ""
    metadata: {pages: 0, sources: [], languages: []}
