
# Extend/override built-in replacements
toabeculas: trabeculae
fotymoyphoys: polymorphous
palato: palate
pala: palate
comozd: composed
microscoplc: microscopic
necrosls: necrosis
cribriforme: cribriform
